name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          3.8.3

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip  # upgrade pip after installing python

    - name: Install pyenv dependencies
      run: pip install -r requirements.txt

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Set Poetry config
      run: |
        poetry config settings.virtualenvs.in-project false
        poetry config settings.virtualenvs.path ~/.virtualenvs

    - name: Install Poetry Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Code Quality
      run: poetry run black . --check

    - name: Test with pytest
      env:
        DJANGO_SETTINGS_MODULE: project.settings
        SECRETS_FILE: .confidential/ci.json
      run: |
        poetry run mypy type-inference/*.py
        poetry run pytest --cov . -n 2
